name: duoob_desktop_app_v1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  auto_size_text: ^3.0.0
  readmore: ^3.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  lottie: ^3.3.2
  path_provider: ^2.1.5
  multi_split_view: ^3.6.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.12
msix_config:
  display_name: Duoob
  publisher_display_name: RAK Properties
  identity_name: io.rak.rakpmsmart
  msix_version: 1.0.0.0
  capabilities: internetClient
  publisher: CN=RAKProperties
  certificate_path: C:\Flutter\Projects\build\my_cert.pfx
  certificate_password: Password123
  logo_path: assets/images/App_Logo.png # Path to your app icon

  package_rename: ^1.10.1
package_rename_config:
  # This sets the name shown on the home screen/taskbar
  app_name: "Duoob"
  
  # This sets the internal ID (e.g., com.example.app)
  package_name: "io.rak.rakpmsmart"

    
  windows:
    app_name: "Duoob"
    organization: "RAK Properties"
    copyright_private_party: ""

  macos:
    app_name: "Duoob" # Product name
    package_name: "io.rak.rakpmsmart" # Product Bundle Identifier
    copyright_notice: "" # Copyright notice


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSan
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
